### ISSUE TITLE
if it is possible to find multiple matches?

### ISSUE THREAD

**Issue by xihajun** [peter-evans/find-comment#117]
Hi, I wonder if this action could find multiple matches? From the readme, it seems that it only supports `first` and `last` matches?

**Comment by xihajun** [comment]
https://github.com/peter-evans/find-comment/blob/dea9995255c24229e57e55462943072f02c4fec8/src/find.ts#L51-L75

Looks like we can change this to return all the matches? Is that a json format?

**Comment by peter-evans** [comment]
Hi @xihajun 

The goal of this action is to find a specific comment, not a list of comments. The main issue with finding multiple comments is returning the output.

I don't think this is something that I want to try and support in this action. My suggestion would be to call the GitHub API yourself for this use case using [github-script](https://github.com/actions/github-script).
