### ISSUE TITLE
Case insensitivity?

### ISSUE THREAD

**Issue by jai** [peter-evans/find-comment#127]
Hi - first of all thanks for this action/code.

I'm using it to...well, find a comment :) and I was trying to make the search case-insensitive.

In the regex, I've tried:
```
\^.*no-experiment.*$\gi << silently fails (no error, but doesn't find "no-experiment" or "no-experimenT")

(?i)^.*no-experiment.*$ << throws an error
```

The error from the second regex is:
```
Error: Invalid regular expression: /(?i)^.*no-experiment.*$/: Invalid group
```

So it seems that the regex start/end `/.../` are being added when the regex is parsed, so I'm unable to add anything outside the regex start/end (no flags i.e. case insensitive).

Do you know of a way I can achieve above? Or I can also submit a PR to make the search for `body-includes` case insensitive if it wasn't intended to be case sensitive (is it?)

**Comment by peter-evans** [comment]
Hi @jai 

I've released an update to fix this issue. The action now supports regex flags in `v2.3.0` / `v2`.

Your first example should now work:
```
\^.*no-experiment.*$\gi
```

Thank you for raising this issue and for your support! ☕ ❤️
