### ISSUE TITLE
nth comment match

### ISSUE THREAD

**Issue by septante** [peter-evans/find-comment#162]
Hi,
Would it be possible to add a parameter to get the nth comment that matches the search criteria? The use case I have in mind involves a tracker issue with multiple comments by the github-actions bot, where each comment corresponds to a different sub-topic and is automatically updated using the `create-or-update-comment` action. It would be nice to be able to, for example, get the third comment by the bot using a parameter instead of having to rely on string matches.

**Comment by peter-evans** [comment]
This feature has been released in `v2.4.0` / `v2`.

Thank you @NiloCK !

**Comment by septante** [comment]
Thank you both!
