### ISSUE TITLE
fetch body of matching comment

### ISSUE THREAD

**Issue by p-costa** [peter-evans/find-comment#23]
Hello @peter-evans , thanks for this very nice tool!

Is there a way of fetching the body of the matching comment? I.e., getting the body of a comment that matched the search keyword?

Thanks in advance!
Pedro

**Comment by peter-evans** [comment]
Hi @p-costa 

I will add an additional output to return the comment body. It will save you needing to make another API call to fetch it.

**Comment by p-costa** [comment]
Thank you! I need this because I need to fetch a keyword on a comment by the bot to trigger an action (after a pull request is merged).

I have an incomplete draft using some of your tools, and this would give me the last thing I'd need: the possibility to modify my comment body using your nice [create-or-update-comment](https://github.com/peter-evans/create-or-update-comment), which is important for my application to make sure the action is only triggered once.

**Comment by peter-evans** [comment]
Output `comment-body` is now available in the latest release.

**Comment by p-costa** [comment]
tested and works like a charm :)
