### ISSUE TITLE
Find the last matching comment

### ISSUE THREAD

**Issue by seisman** [peter-evans/find-comment#33]
> The action will output the comment ID of the first comment matching the search criteria.

I'm wondering if it's possible to find the last comment?

**Comment by peter-evans** [comment]
@seisman It wasn't possible, but it is now! I've just added this as a new feature, released as `v1.2.0` / `v1`. Thank you for suggesting it.

There is a new input, `direction`, that you can set to `last`. See the readme for an example.

**Comment by seisman** [comment]
@peter-evans Great! Thanks for your quick work and the new release!
