### ISSUE TITLE
`comment-author` cannot be printed at this case

### ISSUE THREAD

**Issue by kimhanui** [peter-evans/find-comment#50]
Hi, I'm satisfied with this product. 

However, when I was testing my `github-action` with your product, I found something strange.

After the several tests, I think maybe you didn't deal the case **that `comment-body` contatins `\n` character** for some reason

**These are what I tested...**

>  I used this code at `Find Comment` and `Run echo` step below
>  ```
> - name: Find Comment
>        uses: peter-evans/find-comment@v1.3.0
>        id: fc
>        with:
>            issue-number: 1
>            body-includes: ${{ github.event.comment.body }}
>      - run: |
>          echo ${{ steps.fc.outputs.comment-id }}
>          echo ${{ steps.fc.outputs.comment-body }}
>          echo ${{ steps.fc.outputs.comment-author }}
>  ```

- When I posted an issue comment like (not includes `\n`)
   ```
   [질문] 개행아아아아
   ``` 
  -> get `comment-author` well
  
   ![image](https://user-images.githubusercontent.com/30483337/132102348-784a6b93-f3e5-4a43-8670-6039da16e4ec.png)

- When I posted an issue comment like (inclues `\n`) 
   ```
   [질문]
   개행아아아아
   ``` 
   
   -> it occurs error `개행아아아아 commands not found`. **BUT, actually `개행아아아아` is not a command but a part of `comment-body`**

  ![image](https://user-images.githubusercontent.com/30483337/132102244-e508bd02-da14-4a85-b481-2312cef1290d.png)

- When I posted an issue comment like (not inclues `\n`, `space`)
   ```
   [질문]
   ```
  -> it occurs error `\r command not found`.
   
   ![image](https://user-images.githubusercontent.com/30483337/132101681-e17077b0-4a1b-43fc-a73d-7b0be12baeb7.png)

**Comment by peter-evans** [comment]
Hi @kimhanui 

I think you need to quote the input. I'm not sure if there is a difference between single and double quotes for yaml, but you can try both and see.

e.g.
```diff
      uses: peter-evans/find-comment@v1.3.0
      id: fc
      with:
          issue-number: 1
-         body-includes: ${{ github.event.comment.body }}
+         body-includes: '${{ github.event.comment.body }}'
```

**Comment by kimhanui** [comment]
@peter-evans
oh.... I didn't even imagine it, thanks for answering this. 👍
