### ISSUE TITLE
Crash when comment is too long

### ISSUE THREAD

**Issue by Bill-Yu-Night-Market** [peter-evans/find-comment#60]
![image](https://user-images.githubusercontent.com/90853694/154322921-83a90fc8-118a-48f4-aef3-5caefe67a035.png)

If the comment is long, node doesn't seem to like it as a input parameter, maybe trim the comment?

**Comment by peter-evans** [comment]
Hi @Bill-Yu-Night-Market 

Here's some background to this error:
https://github.com/peter-evans/create-or-update-comment/issues/96

As explained there, the maximum length is determined by the runner, so I would like to avoid hardcoding a limit in the action. It should be fairly easy to truncate the comment in the workflow if necessary.
